# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  RG: 'RG-Bicep-DevOps-Demo'
  templateFile: './bicep-templates/main.bicep'
  templateParameterFile: './bicep-templates/main.parameters.json'

stages:  

- stage: Preview
  jobs: 
  - job: Preview
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'ASHubServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group what-if \
            --template-file $(Build.SourcesDirectory)/$(templateFile) \
            --parameters '$(Build.SourcesDirectory)/$(templateParameterFile)' \
            --resource-group '$(RG)'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Deploy Bicep Files'
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'ASHubServiceConnection'
          subscriptionId: '39aca73e-1d25-4edf-84d5-ebe0397a816b'
          action: 'Create Or Update Resource Group'
          resourceGroupName: '$(RG)'
          location: 'Australia East'
          templateLocation: 'Linked artifact'
          csmFile: 'main.bicep'
          csmParametersFile: 'main.parameters.json'
          deploymentMode: 'Incremental'

- stage: Cleanup
  dependsOn: Deploy
  jobs:
  - job: CleanUp
    steps:
      - task: AzureCLI@2
        displayName: 'Cleanup Resources'
        inputs:
          azureSubscription: 'ASHubServiceConnection'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az group delete --name $(RG) --yes'
